name: example
description: TIMUIkit LBS Plugin example

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_baidu_mapapi_map: ^3.1.0+1
  flutter_baidu_mapapi_base: ^3.1.0
  flutter_baidu_mapapi_search: ^3.1.0
  flutter_baidu_mapapi_utils: ^3.1.0+1
  flutter_bmflocation: ^3.0.0
  tim_ui_kit_lbs_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

publish_to: none